version: "3.7"
services: 
  mysql-db:
    build:
      context: ./db
    image: uopsdod/mysql-db-01
    container_name: mysql-db
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=demo_java
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=demo_db
    networks:
      my-bridge-001:
        ipv4_address: 172.90.1.1
  java-app:
    build:
      context: ./app
    image: uopsdod/java-app-01
    ports:
      - "8080:8080"
    command: ["./wait-for-it.sh", "172.90.0.1:3306", "--", "java", "-jar", "target/accessing-data-mysql-0.0.1-SNAPSHOT.jar"]
    environment:
      - DB_HOST_IP=mysql-db
    networks:
      my-bridge-001:
        ipv4_address: 172.90.1.2

networks:
  my-bridge-001:
    ipam:
      config:
        - subnet: 172.90.0.0/16
