version: "3.7"
services: 
  mysql-db:
    build:
      context: ./db
    image: uopsdod/mysql-db-01
    container_name: mydb
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=demo_java
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=demo_db
    networks:
      my-bridge-001:
  java-app:
    build:
      context: ./app
    image: uopsdod/java-app-01
    ports:
      - "8080:8080"
    command: ./wait-for-it.sh mydb:3306 -- java -jar target/accessing-data-mysql-0.0.1-SNAPSHOT.jar 
    environment:
      - DB_HOST_IP=mydb
    networks:
      my-bridge-001:
  react-web:
    build:
      context: ./web
    image: uopsdod/react-web-01
    ports: 
      - "3000:3000"
    environment:
      - REACT_APP_API_HOST_IP=${API_HOST_IP}


networks:
  my-bridge-001:
